### ISSUE TITLE
Project not buildable, lots of dependency issues when new package-lock.json is built

### ISSUE THREAD

**Issue by supa-freak** [surveyjs/surveyjs-react-client#1]
https://github.com/surveyjs/surveyjs-nodejs/commit/44a63fc0892778f31f768871a1a5570bbcda8b3b
is not buildable anymore.
It is possible with the existing package-lock.json in the repo (which is not the one created from package.json in this commit), but if forced to build a new package-lock.json, it falls apart with loads of dependency issues.
E.g.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: surveyjs-react-client@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"<18.0.0" from @testing-library/react@12.1.5
npm ERR! node_modules/@testing-library/react
npm ERR!   @testing-library/react@"^12.1.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by tsv2013** [comment]
I've added github action building this project on the last node versions - https://github.com/surveyjs/surveyjs-react-client/actions/workflows/build-node.js.yml

It passed ok right now.
